<template>
  <AppLayout>
    <div class="mx-auto max-w-6xl space-y-6">
      <div><h1 class="text-2xl font-semibold">二级代理管理</h1><p class="mt-1 text-sm text-gray-500">仅管理员授权的一级合伙人可使用。平台只与一级代理结算，二级代理由一级代理自行结算。</p></div>
      <div v-if="loading" class="rounded-xl border p-6 text-gray-500">加载中...</div>
      <div v-else-if="!capability?.enabled" class="rounded-xl border border-amber-200 bg-amber-50 p-6 text-amber-800">当前账号尚未获得二级代理权限，请联系管理员开通。</div>
      <template v-else>
        <div class="flex items-center justify-between"><div class="text-sm text-gray-500">已管理 {{ agents.length }} 个二级代理</div><button class="rounded-lg bg-primary-600 px-4 py-2 text-sm text-white" @click="showCreate = true">新增二级代理</button></div>
        <div class="overflow-hidden rounded-xl border bg-white"><table class="min-w-full text-left text-sm"><thead class="bg-gray-50"><tr><th class="px-4 py-3">代理</th><th class="px-4 py-3">邀请码</th><th class="px-4 py-3">分佣比例</th><th class="px-4 py-3">邀请人数</th><th class="px-4 py-3">状态</th><th class="px-4 py-3">操作</th></tr></thead><tbody><tr v-for="agent in agents" :key="agent.id" class="border-t"><td class="px-4 py-3">{{ agent.username || agent.email }}</td><td class="px-4 py-3 font-mono">{{ agent.aff_code }}</td><td class="px-4 py-3"><input class="w-20 rounded border px-2 py-1" type="number" :value="agent.commission_rate" @change="onRateChange(agent, $event)">%</td><td class="px-4 py-3">{{ agent.invited_count }}</td><td class="px-4 py-3">{{ agent.status }}</td><td class="flex gap-3 px-4 py-3"><button class="text-primary-600" @click="inspect(agent)">查看统计</button><button class="text-primary-600" @click="toggle(agent)">{{ agent.status === 'active' ? '停用' : '启用' }}</button></td></tr><tr v-if="!agents.length"><td colspan="6" class="px-4 py-10 text-center text-gray-500">暂无二级代理</td></tr></tbody></table></div>
        <div v-if="selectedAgent" class="rounded-xl border bg-white p-5"><h2 class="font-semibold">{{ selectedAgent.username || selectedAgent.email }} 的统计</h2><div class="mt-4 grid gap-3 sm:grid-cols-4"><div class="rounded-lg bg-gray-50 p-3"><div class="text-xs text-gray-500">请求数</div><div class="text-lg font-semibold">{{ stats?.summary?.total_requests ?? '-' }}</div></div><div class="rounded-lg bg-gray-50 p-3"><div class="text-xs text-gray-500">Token</div><div class="text-lg font-semibold">{{ stats?.summary?.total_tokens ?? '-' }}</div></div><div class="rounded-lg bg-gray-50 p-3"><div class="text-xs text-gray-500">消费金额</div><div class="text-lg font-semibold">{{ stats?.summary?.total_actual_cost ?? '-' }}</div></div><div class="rounded-lg bg-gray-50 p-3"><div class="text-xs text-gray-500">返佣金额</div><div class="text-lg font-semibold">{{ rebatesTotal }}</div></div></div></div>
        <div v-if="showCreate" class="rounded-xl border bg-white p-5"><div class="grid gap-3 sm:grid-cols-3"><div class="relative"><input v-model="candidateQuery" placeholder="搜索邮箱、用户名或用户 ID" class="w-full rounded-lg border px-3 py-2" @input="searchCandidates"><div v-if="candidates.length" class="absolute left-0 right-0 top-full z-10 mt-1 max-h-48 overflow-auto rounded-lg border bg-white shadow"><button v-for="candidate in candidates" :key="candidate.user_id" type="button" class="block w-full px-3 py-2 text-left text-sm hover:bg-gray-50" @click="selectCandidate(candidate)">{{ candidate.username || candidate.email }} <span class="text-gray-400">#{{ candidate.user_id }}</span></button></div></div><input v-model="form.aff_code" placeholder="邀请码（可选）" class="rounded-lg border px-3 py-2"><input v-model.number="form.commission_rate" type="number" placeholder="分佣比例" class="rounded-lg border px-3 py-2"></div><div v-if="form.user_id" class="mt-2 text-sm text-gray-500">已选择用户 ID：{{ form.user_id }}</div><div class="mt-4 flex gap-2"><button class="rounded-lg bg-primary-600 px-4 py-2 text-sm text-white" :disabled="!form.user_id" @click="create">保存</button><button class="rounded-lg border px-3 py-2 text-sm" @click="showCreate = false">取消</button></div></div>
      </template>
    </div>
  </AppLayout>
</template>
<script setup lang="ts">
import AppLayout from '@/components/layout/AppLayout.vue'
import { onMounted, reactive, ref } from 'vue'
import { secondLevelAgencyAPI, type SecondLevelAgent, type SecondLevelAgencyCandidate, type SecondLevelAgencyCapability } from '@/api/secondLevelAgency'
const loading = ref(true); const capability = ref<SecondLevelAgencyCapability | null>(null); const agents = ref<SecondLevelAgent[]>([]); const showCreate = ref(false); const selectedAgent = ref<SecondLevelAgent | null>(null); const stats = ref<any>(null); const rebatesTotal = ref('-'); const candidateQuery = ref(''); const candidates = ref<SecondLevelAgencyCandidate[]>([]); const form = reactive({ user_id: 0, aff_code: '', commission_rate: 0 })
async function load() { loading.value = true; try { capability.value = await secondLevelAgencyAPI.getStatus(); if (capability.value.enabled) agents.value = await secondLevelAgencyAPI.list() } finally { loading.value = false } }
async function create() { await secondLevelAgencyAPI.create(form); showCreate.value = false; form.user_id = 0; form.aff_code = ''; form.commission_rate = 0; await load() }
async function searchCandidates() { if (candidateQuery.value.trim().length < 2) { candidates.value = []; return }; candidates.value = await secondLevelAgencyAPI.candidates(candidateQuery.value) }
function selectCandidate(candidate: SecondLevelAgencyCandidate) { form.user_id = candidate.user_id; candidateQuery.value = candidate.username || candidate.email; candidates.value = [] }
async function toggle(agent: SecondLevelAgent) { await secondLevelAgencyAPI.setStatus(agent.id, agent.status === 'active' ? 'disabled' : 'active'); await load() }
async function setRate(agent: SecondLevelAgent, rate: number) { await secondLevelAgencyAPI.setRate(agent.id, rate); await load() }
function onRateChange(agent: SecondLevelAgent, event: Event) { const target = event.target as HTMLInputElement; void setRate(agent, Number(target.value)) }
async function inspect(agent: SecondLevelAgent) { selectedAgent.value = agent; stats.value = await secondLevelAgencyAPI.usage(agent.id, { view: 'users' }); const rebate = await secondLevelAgencyAPI.rebates(agent.id); rebatesTotal.value = String(rebate?.total ?? '-') }
onMounted(load)
</script>
